# Generated by Django 6.0.6 on 2026-06-29 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloIA',
            fields=[
                ('id_modelo', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_entrenamiento', models.DateTimeField(auto_now_add=True)),
                ('mae', models.DecimalField(decimal_places=4, max_digits=10)),
                ('mape', models.DecimalField(decimal_places=4, max_digits=10)),
                ('estado', models.CharField(max_length=255)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
            options={
                'db_table': 'modeloIA',
            },
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id_prediccion', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('horizonte_dias', models.BigIntegerField()),
                ('demanda_predicha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
            options={
                'db_table': 'prediccion',
            },
        ),
    ]
