# Generated by Django 6.0.6 on 2026-07-13 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModeloIA',
        ),
    ]
