# Generated by Django 6.0.6 on 2026-06-29 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('lead_time_dias', models.BigIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('stock_actual', models.BigIntegerField()),
                ('stock_minimo', models.BigIntegerField()),
                ('stock_maximo', models.BigIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
                ('id_proveedor_principal', models.ForeignKey(db_column='id_proveedor_principal', on_delete=django.db.models.deletion.PROTECT, to='core.proveedor')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
