# Generated by Django 6.0.6 on 2026-07-13 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pedidos', '0002_alter_pedido_id_proveedor'),
        ('proveedores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_proveedor_principal',
            field=models.ForeignKey(db_column='id_proveedor_principal', on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedor'),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
