# Generated by Django 6.0.6 on 2026-07-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('lead_time_dias', models.BigIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
    ]
