// Archivo para pruebas de UI 

import type { Categoria, Movimiento, Producto } from "./api/types";

export const mockMovimientos: Movimiento[] = [
  {
    id: 0,
    producto_nombre: "iPhone 15 Pro",
    tipo_movimiento: "Entrada",
    fecha: new Date("2026-07-01T09:30:00"),
    cantidad: 50,
    observaciones: "Ingreso por compra a proveedor",
  },
  {
    id: 1,
    producto_nombre: "Samsung Galaxy S25",
    tipo_movimiento: "Salida",
    fecha: new Date("2026-07-01T11:15:00"),
    cantidad: 3,
    observaciones: "Venta en tienda",
  },
  {
    id: 2,
    producto_nombre: "Xiaomi 15",
    tipo_movimiento: "Entrada",
    fecha: new Date("2026-07-02T08:45:00"),
    cantidad: 25,
    observaciones: "Reposición de stock",
  },
  {
    id: 3,
    producto_nombre: "Motorola Edge 60",
    tipo_movimiento: "Salida",
    fecha: new Date("2026-07-02T14:20:00"),
    cantidad: 5,
    observaciones: "Pedido mayorista",
  },
  {
    id: 4,
    producto_nombre: "Google Pixel 10",
    tipo_movimiento: "Salida",
    fecha: new Date("2026-07-03T10:00:00"),
    cantidad: 2,
    observaciones: "Venta online",
  },
  {
    id: 5,
    producto_nombre: "iPhone 15 Pro",
    tipo_movimiento: "Salida",
    fecha: new Date("2026-07-03T16:10:00"),
    cantidad: 1,
    observaciones: "Cambio por garantía",
  },
  {
    id: 6,
    producto_nombre: "Samsung Galaxy S25",
    tipo_movimiento: "Entrada",
    fecha: new Date("2026-07-04T09:00:00"),
    cantidad: 40,
    observaciones: "Recepción de mercadería",
  },
  {
    id: 7,
    producto_nombre: "Xiaomi 15",
    tipo_movimiento: "Salida",
    fecha: new Date("2026-07-04T17:30:00"),
    cantidad: 6,
    observaciones: "Venta presencial",
  },
  {
    id: 8,
    producto_nombre: "Motorola Edge 60",
    tipo_movimiento: "Entrada",
    fecha: new Date("2026-07-05T13:15:00"),
    cantidad: 15,
    observaciones: "Transferencia desde almacén central",
  },
  {
    id: 9,
    producto_nombre: "Google Pixel 10",
    tipo_movimiento: "Entrada",
    fecha: new Date("2026-07-05T18:00:00"),
    cantidad: 20,
    observaciones: "Compra a distribuidor",
  },
];

export const mockProductos: Producto[] = [
  {
    id_producto: 1,
    nombre: "Laptop Dell XPS 15",
    sku: "LAP-XPS-001",
    descripcion: 'Laptop de alto rendimiento con pantalla OLED 15.6"',
    precio: 1899.99,
    estado: "critical",
    stock_actual: 0,
    stock_minimo: 5,
    stock_maximo: 30,
    id_categoria: 1,
    categoria_nombre: "Electrónica",
    id_proveedor_principal: 1,
    proveedor_nombre: "Dell Perú",
  },
  {
    id_producto: 2,
    nombre: "Mouse Inalámbrico Logitech MX Master",
    sku: "MOU-LOG-023",
    descripcion: "Mouse ergonómico con conexión Bluetooth",
    precio: 89.99,
    estado: "critical",
    stock_actual: 2,
    stock_minimo: 10,
    stock_maximo: 50,
    id_categoria: 2,
    categoria_nombre: "Accesorios",
    id_proveedor_principal: 2,
    proveedor_nombre: "Logitech",
  },
  {
    id_producto: 3,
    nombre: "Teclado Mecánico RGB",
    sku: "KEY-MEC-045",
    descripcion: "Teclado mecánico con switches Cherry MX",
    precio: 149.99,
    estado: "critical",
    stock_actual: 0,
    stock_minimo: 8,
    stock_maximo: 40,
    id_categoria: 2,
    categoria_nombre: "Accesorios",
    id_proveedor_principal: 3,
    proveedor_nombre: "HyperX",
  },
  {
    id_producto: 4,
    nombre: 'Monitor LG 27" 4K',
    sku: "MON-LG-012",
    descripcion: "Monitor 4K UHD con panel IPS",
    precio: 599.99,
    estado: "critical",
    stock_actual: 3,
    stock_minimo: 6,
    stock_maximo: 25,
    id_categoria: 1,
    categoria_nombre: "Electrónica",
    id_proveedor_principal: 4,
    proveedor_nombre: "LG",
  },
  {
    id_producto: 5,
    nombre: "Webcam HD Logitech C920",
    sku: "WEB-LOG-008",
    descripcion: "Webcam Full HD 1080p",
    precio: 79.99,
    estado: "warning",
    stock_actual: 4,
    stock_minimo: 12,
    stock_maximo: 60,
    id_categoria: 2,
    categoria_nombre: "Accesorios",
    id_proveedor_principal: 2,
    proveedor_nombre: "Logitech",
  },
  {
    id_producto: 6,
    nombre: "Auriculares Sony WH-1000XM5",
    sku: "AUR-SON-019",
    descripcion: "Auriculares con cancelación activa de ruido",
    precio: 349.99,
    estado: "critical",
    stock_actual: 1,
    stock_minimo: 8,
    stock_maximo: 35,
    id_categoria: 3,
    categoria_nombre: "Audio",
    id_proveedor_principal: 5,
    proveedor_nombre: "Sony",
  },
  {
    id_producto: 7,
    nombre: "SSD Samsung 870 EVO 1TB",
    sku: "SSD-SAM-067",
    descripcion: "Disco de estado sólido SATA III",
    precio: 109.99,
    estado: "warning",
    stock_actual: 5,
    stock_minimo: 15,
    stock_maximo: 80,
    id_categoria: 4,
    categoria_nombre: "Almacenamiento",
    id_proveedor_principal: 6,
    proveedor_nombre: "Samsung",
  },
  {
    id_producto: 8,
    nombre: "Cable HDMI 2.1 Premium 2m",
    sku: "CAB-HDM-034",
    descripcion: "Cable HDMI de alta velocidad para 8K",
    precio: 24.99,
    estado: "critical",
    stock_actual: 0,
    stock_minimo: 20,
    stock_maximo: 100,
    id_categoria: 5,
    categoria_nombre: "Cables",
    id_proveedor_principal: 7,
    proveedor_nombre: "UGREEN",
  },
  {
    id_producto: 9,
    nombre: "iPhone 15 Pro 256GB",
    sku: "IPH-15P-256",
    descripcion: "Smartphone Apple con chip A17 Pro",
    precio: 1199.99,
    estado: "warning",
    stock_actual: 12,
    stock_minimo: 10,
    stock_maximo: 40,
    id_categoria: 6,
    categoria_nombre: "Smartphones",
    id_proveedor_principal: 8,
    proveedor_nombre: "Apple",
  },
  {
    id_producto: 10,
    nombre: "AirPods Pro 2da Gen",
    sku: "AIR-PRO-002",
    descripcion: "Auriculares inalámbricos con ANC",
    precio: 249.99,
    estado: "warning",
    stock_actual: 18,
    stock_minimo: 15,
    stock_maximo: 60,
    id_categoria: 3,
    categoria_nombre: "Audio",
    id_proveedor_principal: 8,
    proveedor_nombre: "Apple",
  },
  {
    id_producto: 11,
    nombre: "iPad Air M2 256GB",
    sku: "IPA-AIR-M2",
    descripcion: "Tablet con chip M2 y pantalla Liquid Retina",
    precio: 749.99,
    estado: "normal",
    stock_actual: 8,
    stock_minimo: 5,
    stock_maximo: 25,
    id_categoria: 7,
    categoria_nombre: "Tablets",
    id_proveedor_principal: 8,
    proveedor_nombre: "Apple",
  },
  {
    id_producto: 12,
    nombre: "Apple Watch Series 9",
    sku: "WAT-S9-001",
    descripcion: "Smartwatch con sensor de salud avanzado",
    precio: 399.99,
    estado: "normal",
    stock_actual: 10,
    stock_minimo: 8,
    stock_maximo: 30,
    id_categoria: 8,
    categoria_nombre: "Wearables",
    id_proveedor_principal: 8,
    proveedor_nombre: "Apple",
  },
  {
    id_producto: 13,
    nombre: "Laptop MacBook Pro M3",
    sku: "MAC-M3-001",
    descripcion: "MacBook Pro con chip Apple M3",
    precio: 1999.99,
    estado: "normal",
    stock_actual: 25,
    stock_minimo: 5,
    stock_maximo: 40,
    id_categoria: 1,
    categoria_nombre: "Electrónica",
    id_proveedor_principal: 8,
    proveedor_nombre: "Apple",
  },
  {
    id_producto: 14,
    nombre: "Hub USB-C 7 en 1",
    sku: "HUB-USB-034",
    descripcion: "Concentrador USB-C con HDMI y SD card",
    precio: 49.99,
    estado: "normal",
    stock_actual: 30,
    stock_minimo: 20,
    stock_maximo: 100,
    id_categoria: 2,
    categoria_nombre: "Accesorios",
    id_proveedor_principal: 7,
    proveedor_nombre: "UGREEN",
  },
  {
    id_producto: 15,
    nombre: "Disco Duro Externo 2TB",
    sku: "HDD-EXT-002",
    descripcion: "Disco externo portátil USB 3.0",
    precio: 79.99,
    estado: "normal",
    stock_actual: 22,
    stock_minimo: 10,
    stock_maximo: 60,
    id_categoria: 4,
    categoria_nombre: "Almacenamiento",
    id_proveedor_principal: 9,
    proveedor_nombre: "Seagate",
  },
];

export const mockCategorias: Categoria[] = [
  {
    id_categoria: 1,
    nombre: "Electrónica",
    descripcion: "Dispositivos electrónicos y gadgets",
  },
  {
    id_categoria: 2,
    nombre: "Accesorios",
    descripcion: "Periféricos y accesorios de computadora",
  },
  {
    id_categoria: 3,
    nombre: "Audio",
    descripcion: "Equipos de audio y sonido",
  },
  {
    id_categoria: 4,
    nombre: "Almacenamiento",
    descripcion: "Dispositivos de almacenamiento digital",
  },
  {
    id_categoria: 5,
    nombre: "Cables",
    descripcion: "Cables y conectores",
  },
  {
    id_categoria: 6,
    nombre: "Smartphones",
    descripcion: "Teléfonos inteligentes",
  },
  {
    id_categoria: 7,
    nombre: "Tablets",
    descripcion: "Tabletas digitales",
  },
  {
    id_categoria: 8,
    nombre: "Wearables",
    descripcion: "Dispositivos portables",
  },
];
