INSERT INTO notificacion
(id_notificacion, id_usuario, fecha_creacion, leida, mensaje, titulo)
VALUES
-- Admins
(1,1,NOW()-INTERVAL '5 days',true,'Se realizó correctamente el respaldo automático del sistema.','Respaldo completado'),
(2,1,NOW()-INTERVAL '1 day',false,'Hay una nueva solicitud de aprobación pendiente.','Solicitud pendiente'),
(3,5,NOW()-INTERVAL '2 days',false,'Se detectó un nuevo inicio de sesión desde un dispositivo diferente.','Alerta de seguridad'),
(4,9,NOW()-INTERVAL '3 days',true,'El informe mensual ya se encuentra disponible para revisión.','Informe mensual'),
(5,9,NOW()-INTERVAL '8 hours',false,'Existen cambios pendientes por aprobar en el inventario.','Cambios pendientes'),
(6,13,NOW()-INTERVAL '4 days',true,'La configuración del sistema fue actualizada correctamente.','Configuración actualizada'),
(7,17,NOW()-INTERVAL '12 hours',false,'Se registró una nueva auditoría del sistema.','Nueva auditoría'),
(8,17,NOW()-INTERVAL '2 hours',false,'Revise los permisos asignados a nuevos usuarios.','Revisión de permisos'),
(9,21,NOW()-INTERVAL '6 days',true,'El servidor completó el mantenimiento programado.','Mantenimiento finalizado'),
(10,25,NOW()-INTERVAL '1 day',false,'Hay reportes críticos pendientes de revisión.','Reportes críticos'),
(11,25,NOW()-INTERVAL '30 minutes',false,'Se creó un nuevo usuario con privilegios elevados.','Nuevo administrador'),
(12,29,NOW()-INTERVAL '3 days',true,'La copia de seguridad semanal fue completada.','Backup semanal'),
(13,33,NOW()-INTERVAL '9 hours',false,'Hay una solicitud de modificación de roles pendiente.','Modificar roles'),
(14,37,NOW()-INTERVAL '2 days',true,'El monitoreo del sistema no reporta incidencias.','Estado del sistema'),
(15,41,NOW()-INTERVAL '1 day',false,'Se generó un reporte de actividad administrativa.','Reporte generado'),
(16,41,NOW()-INTERVAL '5 hours',false,'Existen usuarios inactivos para revisión.','Usuarios inactivos'),
(17,45,NOW()-INTERVAL '4 days',true,'Los permisos globales fueron sincronizados.','Permisos sincronizados'),
(18,47,NOW()-INTERVAL '7 hours',false,'Hay una alerta de acceso que requiere validación.','Alerta de acceso'),
-- Gerentes
(19,2,NOW()-INTERVAL '2 days',false,'El reporte de ventas del mes está listo.','Reporte mensual'),
(20,2,NOW()-INTERVAL '4 hours',true,'Se aprobó el presupuesto solicitado.','Presupuesto aprobado'),
(21,6,NOW()-INTERVAL '3 days',true,'Hay nuevas órdenes listas para revisión.','Órdenes pendientes'),
(22,10,NOW()-INTERVAL '8 hours',false,'El inventario presenta productos con bajo stock.','Alerta de inventario'),
(23,14,NOW()-INTERVAL '5 days',true,'Se cerró exitosamente el periodo contable.','Periodo cerrado'),
(24,14,NOW()-INTERVAL '1 day',false,'Revise los indicadores de desempeño del mes.','Indicadores disponibles'),
(25,18,NOW()-INTERVAL '2 days',false,'Se registró una nueva compra importante.','Compra registrada'),
(26,22,NOW()-INTERVAL '6 hours',true,'El equipo completó todas las tareas asignadas.','Tareas completadas'),
(27,26,NOW()-INTERVAL '4 days',false,'Hay solicitudes de vacaciones pendientes de aprobación.','Solicitudes pendientes'),
(28,30,NOW()-INTERVAL '1 day',true,'Se actualizó el tablero de indicadores.','Dashboard actualizado'),
(29,34,NOW()-INTERVAL '9 hours',false,'El proveedor confirmó la entrega del pedido.','Entrega confirmada'),
(30,34,NOW()-INTERVAL '2 hours',false,'Existe una desviación en el presupuesto.','Desviación detectada'),
(31,38,NOW()-INTERVAL '3 days',true,'La reunión semanal fue programada.','Reunión programada'),
(32,42,NOW()-INTERVAL '12 hours',false,'Se requiere aprobación para una nueva compra.','Aprobación requerida'),
(33,46,NOW()-INTERVAL '5 days',true,'El informe financiero fue publicado.','Informe financiero'),
(34,48,NOW()-INTERVAL '7 hours',false,'El desempeño del almacén superó el objetivo mensual.','Buen desempeño'),
(35,48,NOW()-INTERVAL '1 hour',false,'Se recibió un nuevo reporte operativo.','Reporte operativo'),
-- Almaceneros
(36,3,NOW()-INTERVAL '6 hours',false,'El producto A001 alcanzó el stock mínimo.','Stock bajo'),
(37,3,NOW()-INTERVAL '2 days',true,'Se registró correctamente el ingreso de mercancía.','Ingreso registrado'),
(38,7,NOW()-INTERVAL '1 day',false,'Hay pedidos pendientes de despacho.','Despachos pendientes'),
(39,11,NOW()-INTERVAL '5 days',true,'Se realizó un ajuste de inventario.','Inventario actualizado'),
(40,15,NOW()-INTERVAL '3 hours',false,'Se detectó una diferencia durante el conteo físico.','Diferencia de inventario'),
(41,15,NOW()-INTERVAL '1 hour',false,'Revise los productos próximos a vencer.','Productos por vencer'),
(42,19,NOW()-INTERVAL '2 days',true,'El traslado entre almacenes fue completado.','Traslado completado'),
(43,23,NOW()-INTERVAL '10 hours',false,'Hay nuevos productos pendientes de ubicación.','Ubicación pendiente'),
(44,27,NOW()-INTERVAL '4 days',true,'Se actualizó el catálogo de productos.','Catálogo actualizado'),
(45,31,NOW()-INTERVAL '6 hours',false,'Se registró una devolución de mercancía.','Devolución registrada'),
(46,35,NOW()-INTERVAL '3 days',true,'El conteo cíclico finalizó correctamente.','Conteo finalizado'),
(47,35,NOW()-INTERVAL '20 minutes',false,'Se requiere verificar un lote recibido.','Verificación requerida'),
(48,39,NOW()-INTERVAL '2 days',false,'Hay productos pendientes de reabastecimiento.','Reabastecimiento'),
(49,43,NOW()-INTERVAL '1 day',true,'Se completó el despacho del pedido #458.','Despacho completado'),
(50,49,NOW()-INTERVAL '8 hours',false,'Nuevo ingreso de mercancía programado para hoy.','Ingreso programado'),
-- Compradores
(51,4,NOW()-INTERVAL '2 days',false,'El proveedor aceptó la orden de compra enviada.','Orden aceptada'),
(52,8,NOW()-INTERVAL '4 days',true,'Se recibió una nueva cotización.','Nueva cotización'),
(53,8,NOW()-INTERVAL '5 hours',false,'Hay una orden pendiente de aprobación.','Orden pendiente'),
(54,12,NOW()-INTERVAL '1 day',false,'El proveedor modificó la fecha de entrega.','Cambio de entrega'),
(55,16,NOW()-INTERVAL '3 days',true,'La compra fue registrada exitosamente.','Compra registrada'),
(56,20,NOW()-INTERVAL '6 hours',false,'Se requiere seleccionar un proveedor.','Proveedor requerido'),
(57,24,NOW()-INTERVAL '2 days',true,'La factura de compra fue validada.','Factura validada'),
(58,24,NOW()-INTERVAL '30 minutes',false,'Existe una nueva solicitud de compra.','Nueva solicitud'),
(59,28,NOW()-INTERVAL '5 days',true,'Se actualizó la lista de precios.','Precios actualizados'),
(60,32,NOW()-INTERVAL '9 hours',false,'El proveedor confirmó disponibilidad de stock.','Stock confirmado'),
(61,36,NOW()-INTERVAL '2 days',true,'La orden de compra fue enviada correctamente.','Orden enviada'),
(62,40,NOW()-INTERVAL '8 hours',false,'Hay una cotización próxima a vencer.','Cotización por vencer'),
(63,44,NOW()-INTERVAL '3 days',true,'Se aprobó una nueva solicitud de compra.','Solicitud aprobada'),
(64,44,NOW()-INTERVAL '2 hours',false,'Revise las ofertas disponibles de proveedores.','Ofertas disponibles'),
(65,50,NOW()-INTERVAL '1 day',false,'La recepción de la compra fue confirmada.','Compra recibida');
