# Generated by Django 6.0.6 on 2026-07-05 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('proveedores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedor'),
        ),
    ]
