# Generated by Django 6.0.6 on 2026-06-29 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.BigAutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('tipo_alerta', models.CharField(max_length=255)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
            options={
                'db_table': 'alerta',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_movimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=255)),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.BigIntegerField()),
                ('observaciones', models.TextField()),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movimiento_inventario',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('mensaje', models.TextField()),
                ('titulo', models.CharField(max_length=255)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
    ]
