# Generated by Django 6.0.6 on 2026-07-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovimientoInventario',
        ),
    ]
